### ISSUE TITLE
tide fails trying to run a batch

### ISSUE THREAD

**Issue by abayer** [jenkins-x/lighthouse#558]
With this in the logs:

```
{"base-sha":"9b3c92a2ce65a30dbd124fa22a2c5b1a11a4fb87","batch-passing":null,"batch-pending":null,"branch":"master","component":"tide","controller":"sync","file":"/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:1232","func":"github.com/jenkins-x/lighthouse/pkg/tide.(*DefaultController).syncSubpool","level":"info","msg":"Subpool accumulated.","org":"Abayer-UpperCase-Org","prs-missing":[8,7,6],"prs-passing":null,"prs-pending":null,"repo":"environment-lh-tide-rerun-dev","time":"2020-02-28T17:34:24Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1783296]

goroutine 1267 [running]:
github.com/jenkins-x/lighthouse/pkg/prow/git.(*client).getCredentials(0xc000396990, 0x0, 0x0, 0x0, 0x0)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/prow/git/git.go:106 +0x76
github.com/jenkins-x/lighthouse/pkg/prow/git.(*client).Clone(0xc000396990, 0xc0006c0b40, 0x32, 0x0, 0x0, 0x0)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/prow/git/git.go:136 +0xe4
github.com/jenkins-x/lighthouse/pkg/tide.(*DefaultController).pickBatch(0xc0000cf1e0, 0xc000298460, 0xc00094cb20, 0x14, 0xc00094ca80, 0x1d, 0xc0007f0b98, 0x6, 0xc000730990, 0x28, ...)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:820 +0x4ab
github.com/jenkins-x/lighthouse/pkg/tide.(*DefaultController).takeAction(0xc0000cf1e0, 0xc000298460, 0xc00094cb20, 0x14, 0xc00094ca80, 0x1d, 0xc0007f0b98, 0x6, 0xc000730990, 0x28, ...)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:1107 +0x3c8
github.com/jenkins-x/lighthouse/pkg/tide.(*DefaultController).syncSubpool(0xc0000cf1e0, 0xc000298460, 0xc00094cb20, 0x14, 0xc00094ca80, 0x1d, 0xc0007f0b98, 0x6, 0xc000730990, 0x28, ...)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:1241 +0x10c9
github.com/jenkins-x/lighthouse/pkg/tide.(*DefaultController).Sync.func2(0xc00096c120)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:366 +0x13b
github.com/jenkins-x/lighthouse/pkg/tide.subpoolsInParallel.func1(0xc0007c33d0, 0xc0001b26c0, 0xc00038f5c0)
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:436 +0x6e
created by github.com/jenkins-x/lighthouse/pkg/tide.subpoolsInParallel
	/home/abayer/go/src/github.com/jenkins-x/lighthouse/pkg/tide/tide.go:433 +0x19b
```

**Comment by abayer** [comment]
Specifically, we're not setting credentials to the git client passed to the tide controller.

**Comment by abayer** [comment]
And it looks like this is going to be a slightly complex thing to fix due to the GitHub App mode. Yaaaay.
