### ISSUE TITLE
Plumber/launcher client sometimes somehow ends up as nil in trigger.go

### ISSUE THREAD

**Issue by abayer** [jenkins-x/lighthouse#630]
I'm really confused by this one, but I've seen nil-pointers show up once in a while that seem to be due to what's currently the `c.PlumberClient` being nil in `trigger.runRequested(...)`. This crashes the controller, of course. Trying to debug this now.

**Comment by abayer** [comment]
I haven't seen this show up again since I opened it, so...gonna close for now.

**Comment by abayer** [comment]
Dangit, this showed up again. 

```
{"Branch":"master","Clone":"https://github.com/cloudbees/jx-tenant-service.git","ID":"186003333","Link":"https://github.com/cloudbees/jx-tenant-service","Name":"jx-tenant-service","Namespace":"cloudbees","Webhook":"pull_request","author":"jenkins-x-bot","event-GUID":"e2048b00-849a-11ea-8ac5-7621e2e610d7","job":"pr-build","level":"info","msg":"Creating a new LighthouseJob.","name":"e4267cab-849a-11ea-b03f-cae5cab3f9e1","org":"cloudbees","plugin":"trigger","pr":715,"repo":"jx-tenant-service","time":"2020-04-22T13:12:17Z","type":"presubmit","url":"https://github.com/cloudbees/jx-tenant-service/pull/715.diff"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1707bff]

goroutine 14995 [running]:
github.com/jenkins-x/lighthouse/pkg/plugins/trigger.runRequested(0x1fb7f00, 0xc000dde100, 0x0, 0x0, 0xc000307000, 0xc000f38850, 0x1f6cce0, 0xc000ca8150, 0xc0012b04d8, 0xc000c52600, ...)
	/workspace/source/pkg/plugins/trigger/trigger.go:258 +0x45f
github.com/jenkins-x/lighthouse/pkg/plugins/trigger.RunAndSkipJobs(0x1fb7f00, 0xc000dde100, 0x0, 0x0, 0xc000307000, 0xc000f38850, 0x1f6cce0, 0xc000ca8150, 0xc0012b04d8, 0xc000c52600, ...)
	/workspace/source/pkg/plugins/trigger/trigger.go:220 +0x2f3
github.com/jenkins-x/lighthouse/pkg/plugins/trigger.buildAll(0x1fb7f00, 0xc000dde100, 0x0, 0x0, 0xc000307000, 0xc000f38850, 0x1f6cce0, 0xc000ca8150, 0xc0012b04d8, 0xc00024cb70, ...)
	/workspace/source/pkg/plugins/trigger/pull-request.go:222 +0x2e3
github.com/jenkins-x/lighthouse/pkg/plugins/trigger.handlePR(0x1fb7f00, 0xc000dde100, 0x0, 0x0, 0xc000307000, 0xc000f38850, 0x1f6cce0, 0xc000ca8150, 0xc0009d7ec0, 0x4, ...)
	/workspace/source/pkg/plugins/trigger/pull-request.go:51 +0xd35
github.com/jenkins-x/lighthouse/pkg/plugins/trigger.handlePullRequest(0x1f999c0, 0xc00025a0c0, 0xc000dde100, 0x0, 0x0, 0x1f6cce0, 0xc000ca8150, 0x1f7f0a0, 0xc000664510, 0x0, ...)
	/workspace/source/pkg/plugins/trigger/trigger.go:146 +0x2b5
github.com/jenkins-x/lighthouse/pkg/webhook.(*Server).HandlePullRequestEvent.func1(0xc000da28a0, 0xc000527378, 0xc0009fc000, 0xc000aeb860, 0x7, 0x1d1e0b8)
	/workspace/source/pkg/webhook/events.go:196 +0x2c2
created by github.com/jenkins-x/lighthouse/pkg/webhook.(*Server).HandlePullRequestEvent
	/workspace/source/pkg/webhook/events.go:188 +0x5bb
```
